# Generated by Django 5.0.4 on 2024-04-16 19:51

import my_clip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=30)),
                ('image_data', models.JSONField(default=my_clip.models.default_array)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
