# Generated by Django 5.0.4 on 2024-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clip', '0002_alter_storedimage_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedimage',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
