# Generated by Django 5.0.4 on 2024-04-30 20:14

import my_clip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clip', '0003_alter_storedimage_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredInternalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('caption', models.CharField(default='', max_length=300)),
                ('image_data', models.JSONField(default=my_clip.models.default_array)),
            ],
        ),
        migrations.AlterField(
            model_name='storedimage',
            name='caption',
            field=models.CharField(default='', max_length=300),
        ),
    ]
